name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Run Meson and test
  
    strategy:
      matrix:
        os: [ubuntu-22.04]
        buildType: [Debug, Release]
        
    runs-on: ${{ matrix.os }}

    env:
      BUILD_TYPE: ${{ matrix.buildType }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install needed dev packages
      run: ./install.sh

    - name: Everything
      run: meson setup builddir && cd builddir && meson compile && ./GTSL_Test