name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Run CMake and test
  
    strategy:
      matrix:
        os: [ubuntu-22.04]
        buildType: [Debug, Release]
        
    runs-on: ${{ matrix.os }}

    env:
      BUILD_TYPE: ${{ matrix.buildType }}
  
      name: Install X11 dev tools
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libx11-dev

    steps:
    - uses: actions/checkout@v3
    
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset=gcc-test -DCMAKE_CXX_COMPILER=g++-11

    - name: Build
      run: cmake --build --preset=linux-x64-test --config=${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --preset=linux-test
